import dns from "dns";
dns.setServers(["8.8.8.8", "8.8.4.4"]);
import express from "express";
import mongoose from "mongoose";
// import jwt from "jsonwebtoken"; // Removed JWT
import User from "./models/User.js";
import cors from "cors";
import "dotenv/config";
import { createServer } from "http";
import { Server } from "socket.io";
import path from "path";
import { fileURLToPath } from "url";
import session from "express-session";
import MongoStore from "connect-mongo";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Routes - assumed imports based on usage
import trips from "./routes/trips.js";
import bookingRoutes from "./routes/bookings.js";
import authRoutes from "./routes/auth.js";
import userRoutes from "./routes/users.js";
import notificationRoutes from "./routes/notifications.js";

import organiserRoutes from "./routes/organiser.js";

import Booking from "./models/Booking.js";
import Trip from "./models/Trip.js";
import Notification from "./models/Notification.js";

const app = express();
app.set('trust proxy', 1); // Trust Render's load balancer for secure cookies
const httpServer = createServer(app);

// Session Secret Configuration
const SESSION_SECRET = process.env.SESSION_SECRET || "default_dev_secret_autogenerated_" + Math.random().toString(36).substring(7);
if (!process.env.SESSION_SECRET) {
    console.log("ℹ️  NOTICE: Using auto-generated SESSION_SECRET (safe for dev/demos). Configure in Render Dashboard for persistence.");
    process.env.SESSION_SECRET = SESSION_SECRET;
}

const io = new Server(httpServer, {
    cors: {
        origin: ["http://localhost:5173", "http://localhost:3000"], // Explicit origins for credentials
        credentials: true,
        methods: ["GET", "POST"]
    }
});

// Make io accessible to our router
app.set('io', io);

// Middleware
app.use(express.json());

// CORS Configuration for Sessions
app.use(cors({
    origin: ["http://localhost:5173", "http://localhost:3000"], // Match your frontend URL
    credentials: true
}));

// Session Middleware
const sessionMiddleware = session({
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: false,
    store: MongoStore.create({
        mongoUrl: process.env.MONGO_URI,
        collectionName: 'sessions',
        ttl: 14 * 24 * 60 * 60 // 14 days
    }),
    cookie: {
        maxAge: 1000 * 60 * 60 * 24 * 14, // 14 days
        httpOnly: true, // Prevents JS access
        secure: process.env.NODE_ENV === 'production', // Cookie only sent over HTTPS in production
        sameSite: process.env.NODE_ENV === 'production' ? 'none' : 'lax' // 'lax' is fine for localhost
    }
});

app.use(sessionMiddleware);

// Share session with Socket.IO (Basic wrapper)
const wrap = middleware => (socket, next) => middleware(socket.request, {}, next);
io.use(wrap(sessionMiddleware));

// Routes
app.use("/api/trips", trips);
app.use("/api/bookings", bookingRoutes);
app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/notifications", notificationRoutes);

app.use("/api/organiser", organiserRoutes);

const PORT = process.env.PORT || 5000;

// Socket.IO Logic - Updated for Session
io.use(async (socket, next) => {
    try {
        const session = socket.request.session;
        if (!session || !session.user) {
            console.log("Socket Auth Failed: No Session");
            return next(new Error("Authentication error: No session found"));
        }

        // Fetch user to get latest status and username
        const user = await User.findById(session.user.id);
        if (!user || (!user.isVerified)) {
            return next(new Error("User not verified"));
        }

        socket.user = user;
        next();
    } catch (err) {
        console.error("Socket Auth Error:", err);
        next(new Error("Authentication error"));
    }
});

io.on("connection", (socket) => {
    const userId = socket.user.id;
    socket.join(`user_${userId}`);
    console.log(`User Connected: ${socket.id}, UserID: ${userId}`);



    socket.on("disconnect", () => {
        console.log("User Disconnected", socket.id);
    });
});

// Database Connection
mongoose.connect(process.env.MONGO_URI)
    .then(() => {
        console.log("✅ MongoDB Connected");
        console.log("DB Name:", mongoose.connection.name);
        console.log("Ready State:", mongoose.connection.readyState);
    })
    .catch((err) => console.error("❌ MongoDB Connection Error:", err));

// Serve Static files in Production
const buildPath = path.join(__dirname, "../client/dist");
app.use(express.static(buildPath));

// Standard SPA Catch-All
app.get("*", (req, res) => {
    res.sendFile(path.join(buildPath, "index.html"));
});

// Start Server
httpServer.listen(PORT, () => {
    console.log(`🚀 Server running on port ${PORT}`);
});
